//!start login process
//TODO: http://localhost
//TODO: http://localhost:8081
//TODO: https://expo--signin-firebase-fbfb6.firebaseapp.com

//!redirect to application
//TODO: https://expo--signin-firebase-fbfb6.firebaseapp.com/__/auth/handler

